services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
#  db1:
#    image: postgres:16.3-alpine3.20
#    restart: always
#    container_name: integration-tests-prisma
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: tests
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    container_name: local_development
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command:
      - -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
