services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
